version: '3'
services:
 webserver:
  build: ./server
  ports: 
   - "3001:3000"
 client:
  build: ./client
  ports:
   - "3002:4200"
  volumes:
   - ./client:/usr/src/app
   - /usr/src/app/node_modules
